# Régression logistique - Exercices tirés du MOOC d'Andrew Ng

## Chargement des données

Le jeu de données représente les chances de différents étudiants d'être admis à un programme universitaire en fonction de leurs résultats à deux examens

### Charger les données du fichier ex2data1.csv

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("ex2data1.csv")
data.head()

exam1      exam2  admission
0  34.623660  78.024693          0
1  30.286711  43.894998          0
2  35.847409  72.902198          0
3  60.182599  86.308552          1
4  79.032736  75.344376          1

In [3]:
data.sample()
data

exam1      exam2  admission
0   34.623660  78.024693          0
1   30.286711  43.894998          0
2   35.847409  72.902198          0
3   60.182599  86.308552          1
4   79.032736  75.344376          1
5   45.083277  56.316372          0
6   61.106665  96.511426          1
7   75.024746  46.554014          1
8   76.098787  87.420570          1
9   84.432820  43.533393          1
10  95.861555  38.225278          0
11  75.013658  30.603263          0
12  82.307053  76.481963          1
13  69.364589  97.718692          1
14  39.538339  76.036811          0
15  53.971052  89.207350          1
16  69.070144  52.740470          1
17  67.946855  46.678574          0
18  70.661510  92.927138          1
19  76.978784  47.575964          1
20  67.372028  42.838438          0
21  89.676776  65.799366          1
22  50.534788  48.855812          0
23  34.212061  44.209529          0
24  77.924091  68.972360          1
25  62.271014  69.954458          1
26  80.190181  44.821629          1
27  93.114389  38.800670          0
28  61.830206  50.256108          0
29  38.785804  64.995681          0
..        ...        ...        ...
70  32.722833  43.307173          0
71  64.039320  78.031688          1
72  72.346494  96.227593          1
73  60.457886  73.094998          1
74  58.840956  75.858448          1
75  99.827858  72.369252          1
76  47.264269  88.475865          1
77  50.458160  75.809860          1
78  60.455556  42.508409          0
79  82.226662  42.719879          0
80  88.913896  69.803789          1
81  94.834507  45.694307          1
82  67.319257  66.589353          1
83  57.238706  59.514282          1
84  80.366756  90.960148          1
85  68.468522  85.594307          1
86  42.075455  78.844786          0
87  75.477702  90.424539          1
88  78.635424  96.647427          1
89  52.348004  60.769505          0
90  94.094331  77.159105          1
91  90.448551  87.508792          1
92  55.482161  35.570703          0
93  74.492692  84.845137          1
94  89.845807  45.358284          1
95  83.489163  48.380286          1
96  42.261701  87.103851          1
97  99.315009  68.775409          1
98  55.340018  64.931938          1
99  74.775893  89.529813          1

[100 rows x 3 columns]

### Visualiser les données

Vous pouvez vous amuser à reproduire ce graphe avec les librairies Python, mais ne perdez pas trop de temps là-dessus non plus, il y a beaucoup à faire après!

<img src="figure-1.png">

### Découpez vos données en une matrice X et un vecteur y et transformerz-les en array numpy

In [4]:
X = data[:75].as_matrix(('exam1', 'exam2'))
y = np.array(data[:75]['admission'])
n = X.shape[1]
X = np.insert(X, 0, 1,  axis=1)

In [5]:
print("X", X.shape, X[:10])
print("y", y.shape, y[:10])
print(n)

X (75, 3) [[  1.          34.62365962  78.02469282]
 [  1.          30.28671077  43.89499752]
 [  1.          35.84740877  72.90219803]
 [  1.          60.18259939  86.3085521 ]
 [  1.          79.03273605  75.34437644]
 [  1.          45.08327748  56.31637178]
 [  1.          61.10666454  96.51142588]
 [  1.          75.02474557  46.55401354]
 [  1.          76.0987867   87.42056972]
 [  1.          84.43281996  43.53339331]]
y (75,) [0 0 0 1 1 0 1 1 1 1]
2


Vérifiez bien les dimensions de vos structures de données (X.shape)  
La matrice X doit-elle être de dimensions m x n ou bien m x (n+1) ? Quelle est la valeur de n?

### Initialisez theta en un vecteur de zéros

Combien de zéros vous faudra-t-il....?

In [6]:
theta = np.zeros(n+1, dtype=float)

## Formulation de l'hypothèse

Revoyez l'équation de l'hypothèse de la régression logistique. Le produit de theta et de X est enveloppé dans une fonction g(z) qui correspond à la fonction sigmoïde. Nous allons commencer par coder cette fonction.

### Écrivez une fonction _sigmoid_ qui applique la sigmoïde à son argument et retourne le résultat. Si elle reçoit une matrice ou un vecteur en input, elle doit s'appliquer sur chaque élément individuellement et retourner une structure de mêmes dimensions

In [7]:
import math
from scipy.stats import expon

def sigmoid(z):
    return (1./(1. + np.exp(-z)))

Vérifiez votre fonction. Quelle valeur renvoie une sigmoïde si z=0? Si z est grand? Si z est petit?  
Il est possible que vous ayez un lorsque la fonction exponentielle reçoit des valeurs trop grandes. Dans ce cas vous pourrez éventuellement remplacer votre fonction sigmoïde par celle de scipy pour éviter des problèmes dans le reste de votre implémentation.

### Écrivez une fonction _predict_, qui correspond à l'hypohèse hθ(x), qui prend en paramètres X et theta, les multiplie (attention à l'ordre!), applique la fonction sigmoide, et se débrouille pour que le résultat final soit un vecteur de 1 et 0 correspondant aux catégories

In [8]:
def predict(X, theta):
    z = np.dot(X, theta)
    res = sigmoid(z)
    return (res)
    
predict(X, theta)

array([ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

## Entraînement du modèle

### Définissez la fonction de coût de votre modèle

In [9]:
def cost(X, y, theta):
    m = X.shape[0]
    err = predict(X, theta)
    return ((-1/m) * (np.sum(np.dot(np.log(err), y)) + np.dot(np.log(1 - err), (1 - y))))

### Appelez votre fonction _cost_. Vous devriez obtenir une valeur d'environ 0.693

In [10]:
cost(X, y, theta)

0.69314718055994506

### Écrivez une fonction _fit_ qui prend en arguments le vecteur X et le vecteur y des données d'entraînement et renvoie le vecteur de paramètres _theta_ qui a été appris, ainsi que l'évolution du coût

Noter que l'exercice original ne fait pas faire la descente du gradient pour entraîner le modèle, mais plutôt une fonction d'optimisation avancée (_fminunc_ en Matlab). Nous tenterons de faire quand même la descente du gradient. Les plus téméraires peuvent aussi trouver une fonction d'optimisation équivalente en Python et comparer les résultats.

In [11]:
def fit(X, y, theta, alpha, num_iters):
    # Initialiser certaines variable utiles
    m = X.shape[0]
    J_history = []
    
    # Boucler sur le nombre d'itérations
    for _ in range(num_iters):
        err = predict(X, theta) - y
        theta = theta - (alpha / m) * np.dot(err, X)
        J_history.append(cost(X, y, theta))     
        # Effectuer une itération de descente du gradient (i.e. on update theta une fois)
        

    return theta, J_history

### Lancez l'apprentissage en appelant la fonction _fit_ et en prenant bien soin de récupérer le résultat de *theta* à la fin!!

Voyez entre vous quelles valeurs semblent correctes pour alpha et num_iters

In [25]:
theta_fin, J_history_fin = fit(X, y, theta, 0.001, 5500000)
print(theta_fin, J_history_fin[-30:])

[-24.00582054   0.20126224   0.18241038] [0.19502396730255242, 0.19502396699521396, 0.19502396668787578, 0.19502396638053779, 0.19502396607320002, 0.19502396576586242, 0.1950239654585251, 0.19502396515118794, 0.19502396484385112, 0.19502396453651438, 0.19502396422917795, 0.19502396392184168, 0.19502396361450561, 0.19502396330716987, 0.19502396299983421, 0.19502396269249889, 0.19502396238516367, 0.19502396207782885, 0.19502396177049411, 0.19502396146315956, 0.19502396115582535, 0.19502396084849125, 0.19502396054115742, 0.1950239602338239, 0.19502395992649044, 0.19502395961915722, 0.19502395931182431, 0.19502395900449154, 0.19502395869715908, 0.19502395838982675]


### Appelez la fonction _cost_ avec le nouveau theta après entraînement

Vous devriez obtenir une valeur autour de 0.203

In [26]:
cost(X, y, theta_fin)

0.19502395838982675

In [19]:
cost(X, y, theta_fin)0.004

0.1945657111071584

In [17]:
cost(X, y, theta_fin)0.0015

0.19464247585398994

In [14]:
cost(X, y, theta_fin)0.003

0.19456602734514122

In [21]:
cost(X, y, theta_fin)0.005

0.22135047989907114

### On visualise maintenant l'évolution du coût en fonction du nombre d'itérations

In [28]:
import matplotlib.pyplot as plt

fig = plt.figure()
ax = plt.axes()
ax.plot(J_history_fin)

## Évaluation de votre modèle

Nous allons évaluer la performance du modèle de deux façons:

### Évaluez la probabilité qu'un étudiant ayant obtenu 45 au premier examen, et 85 au deuxième, soit admis

Vous devriez avoir une probabilité d'admission de 0.776

In [36]:
predict(np.array([1, 45, 85]), theta_fin)

0.63549458550275928

### Évaluer l'exactitude (accuracy) des prédictions faites sur les données d'entraînement

Utilisez votre fonction _predict_ sur les données d'entraînement (X) et récupérez les prédictions dans un vecteur p

In [40]:
X = data[75:].as_matrix(('exam1', 'exam2'))
y = np.array(data[75:]['admission'])
n = X.shape[1]
X = np.insert(X, 0, 1,  axis=1)

p = predict(X, theta)

Calculez le pourcentage des éléments de p qui correspondent à ceux de y. Ça vous donne le score d'exactitude

In [35]:
predict()

Vous devriez avoir un score d'environ 89.0 %

## BONUS: Visualisez la frontière de décision (decision boundary) sur le graphe

Pour ceux qui veulent découvrir Matplotlib, il faut ici afficher les données en deux nuages de points distincts (pour les deux classes) sur le même graphe, et aussi trouver une façon de tracer la fonction qui définit la frontière de décision. Amusez-vous bien, et surtout aidez-vous! Ça devrait donner un truc du genre:  
<img src="figure-2.png">